import type { Banner } from '@/api/types';

/** Fallback when GET /banners is empty / unreachable — keep Home carousels populated. */
export const FALLBACK_HOME_BANNERS: Banner[] = [
  {
    id: 'fallback-hero-openclaw',
    title: 'OpenClaw trên AI Markets',
    subtitle: 'Launch agent Control UI — provider cost + 25%',
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200&q=80',
    linkType: 'agents',
    linkValue: '',
    slot: 'home_hero',
    sortOrder: 10,
  },
  {
    id: 'fallback-hero-work',
    title: 'Work trên AI Markets',
    subtitle: 'Tìm việc · thuê nhân tài · đăng tuyển dụng',
    imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&q=80',
    linkType: 'url',
    linkValue: '/work',
    slot: 'home_hero',
    sortOrder: 15,
  },
  {
    id: 'fallback-hero-hermes',
    title: 'Hermes Agent',
    subtitle: 'Dashboard trên hermes.aimarkets.vn',
    imageUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1200&q=80',
    linkType: 'agents',
    linkValue: '',
    slot: 'home_hero',
    sortOrder: 20,
  },
  {
    id: 'fallback-hero-explore',
    title: 'Khám phá catalog',
    subtitle: 'API · Models · GPU · Licenses',
    imageUrl: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=1200&q=80',
    linkType: 'explore',
    linkValue: '',
    slot: 'home_hero',
    sortOrder: 30,
  },
  {
    id: 'fallback-offer-gpu',
    title: 'Ưu đãi GPU inference',
    subtitle: 'Giảm phí chạy model qua marketplace',
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80',
    linkType: 'category',
    linkValue: 'inference',
    slot: 'offers',
    sortOrder: 10,
  },
  {
    id: 'fallback-offer-license',
    title: 'License nội dung số',
    subtitle: 'Mua key hợp lệ — xem ngay trong app',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80',
    linkType: 'explore',
    linkValue: '',
    slot: 'offers',
    sortOrder: 20,
  },
  {
    id: 'fallback-partner-creator',
    title: 'Đối tác creator',
    subtitle: 'Shop doanh thu nổi bật trên AI Markets',
    imageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80',
    linkType: 'explore',
    linkValue: '',
    slot: 'partners',
    sortOrder: 10,
  },
];
